export const bearerToken =
    // tslint:disable-next-line:max-line-length
    'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MiIsImVtYWlsIjoiam9obkBzbm93LmNvbSIsIm5hbWUiOiJKb2huIFNub3ciLCJleHAiOjE1OTUyNzM2NzksImlzcyI6Imh0dHBzOi8vZGlnaXRhbG1hcmtldHMuY28iLCJzY29wZXMiOlsia3djOmdlbmVyYWwiLCJ4YXZpZXI6Z2VuZXJhbCIsInhhdmllcjpzdWJtaXNzaW9uczp2aWV3IiwieGF2aWVyOnN1Ym1pc3Npb25zOm1hbmFnZSIsInhhdmllcjpjYXRhbG9nOnZpZXciLCJ4YXZpZXI6ZGV2ZWxvcGVycyIsImRhYXM6dmlldyIsImRhYXM6ZWRpdCIsImRhYXM6bWFuYWdlIl19._oHHX0VWKkCYr_t5U9ekqTj0qYhrWCVU0kyZ6070N1k';
